name: optviz
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - altair=5.0.1
  - astroid=3.3.8
  - attrs=24.3.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cycler=0.11.0
  - dill=0.3.8
  - fonttools=4.55.3
  - freetype=2.12.1
  - gitpython=3.1.43
  - icu=73.1
  - idna=3.7
  - importlib_resources=6.4.0
  - isort=5.13.2
  - jinja2=3.1.5
  - jpeg=9e
  - jsonschema=4.23.0
  - kiwisolver=1.4.4
  - lcms2=2.16
  - libdeflate=1.22
  - libpng=1.6.39
  - libtiff=4.5.1
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - mccabe=0.7.0
  - numpy=2.0.2
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.0
  - plotly=6.0.0
  - protobuf=4.25.3
  - pyarrow=19.0.0
  - pygments=2.15.1
  - pylint=3.3.3
  - pyparsing=3.2.0
  - python-dateutil=2.9.0post0
  - python==3.9.19
  - pytz=2024.1
  - requests=2.32.3
  - rich=13.9.4
  - seaborn=0.13.2
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - streamlit=1.41.1
  - tenacity=9.0.0
  - tk=8.6.14
  - toml=0.10.2
  - tornado=6.4.2
  - typing-extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - conda-forge::spacy
  - pip:
        - dotenv
        - openai
        - pinecone
        - langchain
        - newsapi-python
        - py_vollib
        - sentence_transformers
        - yfinance